In [2]:
import pandas as pd

In [4]:
# Load your file
df = pd.read_excel("My_Statement_DataSet.xlsx")

In [6]:
# Step 1: Forward fill missing values
df = df.ffill()

In [9]:
df.head()

,S No.,Value Date,Transaction Date,Cheque Number,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR)
0,1.0,01/04/2025,01/04/2025,NaN,UPI/gauravchandigar/UPI/Punjab and Sind/509120...,38550.00,0.0,50973.49
1,2.0,01/04/2025,01/04/2025,NaN,UPI/thappavansh2-2@/UPI/State Bank Of I/545772...,0.00,38550.0,89523.49
2,3.0,02/04/2025,02/04/2025,NaN,UPI/goog-payments@a/UPI/AXIS BANK/756687000925...,0.00,6.0,89529.49
3,4.0,02/04/2025,02/04/2025,NaN,UPI/zomatoonlineord/ZomatoOnlineOrd/AIRTEL PAY...,196.15,0.0,89333.34
4,5.0,03/04/2025,03/04/2025,NaN,UPI/swiggyupi@axb/Pay for Intent/AXIS BANK/509...,142.00,0.0,89191.34

In [11]:
df.isnull().sum()

S No.                       0
Value Date                  0
Transaction Date            0
Cheque Number             503
Transaction Remarks         0
Withdrawal Amount(INR)      0
Deposit Amount(INR)         0
Balance(INR)                0
dtype: int64

In [12]:
df = df.drop(columns=['Cheque Number'])

In [13]:
df.head()

,S No.,Value Date,Transaction Date,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR)
0,1.0,01/04/2025,01/04/2025,UPI/gauravchandigar/UPI/Punjab and Sind/509120...,38550.00,0.0,50973.49
1,2.0,01/04/2025,01/04/2025,UPI/thappavansh2-2@/UPI/State Bank Of I/545772...,0.00,38550.0,89523.49
2,3.0,02/04/2025,02/04/2025,UPI/goog-payments@a/UPI/AXIS BANK/756687000925...,0.00,6.0,89529.49
3,4.0,02/04/2025,02/04/2025,UPI/zomatoonlineord/ZomatoOnlineOrd/AIRTEL PAY...,196.15,0.0,89333.34
4,5.0,03/04/2025,03/04/2025,UPI/swiggyupi@axb/Pay for Intent/AXIS BANK/509...,142.00,0.0,89191.34

In [14]:
df.isnull().sum()

S No.                     0
Value Date                0
Transaction Date          0
Transaction Remarks       0
Withdrawal Amount(INR)    0
Deposit Amount(INR)       0
Balance(INR)              0
dtype: int64

In [15]:
# Step 2: Combine description columns if split
df['description'] = df.iloc[:, 1:].astype(str).agg(' '.join, axis=1)

In [16]:
df.head()

,S No.,Value Date,Transaction Date,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR),description
0,1.0,01/04/2025,01/04/2025,UPI/gauravchandigar/UPI/Punjab and Sind/509120...,38550.00,0.0,50973.49,01/04/2025 01/04/2025 UPI/gauravchandigar/UPI/...
1,2.0,01/04/2025,01/04/2025,UPI/thappavansh2-2@/UPI/State Bank Of I/545772...,0.00,38550.0,89523.49,01/04/2025 01/04/2025 UPI/thappavansh2-2@/UPI/...
2,3.0,02/04/2025,02/04/2025,UPI/goog-payments@a/UPI/AXIS BANK/756687000925...,0.00,6.0,89529.49,02/04/2025 02/04/2025 UPI/goog-payments@a/UPI/...
3,4.0,02/04/2025,02/04/2025,UPI/zomatoonlineord/ZomatoOnlineOrd/AIRTEL PAY...,196.15,0.0,89333.34,02/04/2025 02/04/2025 UPI/zomatoonlineord/Zoma...
4,5.0,03/04/2025,03/04/2025,UPI/swiggyupi@axb/Pay for Intent/AXIS BANK/509...,142.00,0.0,89191.34,03/04/2025 03/04/2025 UPI/swiggyupi@axb/Pay fo...

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 983 entries, 0 to 982
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   S No.                   983 non-null    float64
 1   Value Date              983 non-null    str
 2   Transaction Date        983 non-null    str
 3   Transaction Remarks     983 non-null    str
 4   Withdrawal Amount(INR)  983 non-null    float64
 5   Deposit Amount(INR)     983 non-null    float64
 6   Balance(INR)            983 non-null    float64
 7   description             983 non-null    str
dtypes: float64(4), str(4)
memory usage: 61.6 KB

In [18]:
# Step 3: Extract amount & balance (adjust column index if needed)
df['amount'] = df['Deposit Amount(INR)'] - df['Withdrawal Amount(INR)']

In [19]:
df['balance'] = df['Balance(INR)']

In [24]:
df.head()

,transaction date,description,amount,balance
0,01/04/2025,01/04/2025 01/04/2025 UPI/gauravchandigar/UPI/...,-38550.00,50973.49
1,01/04/2025,01/04/2025 01/04/2025 UPI/thappavansh2-2@/UPI/...,38550.00,89523.49
2,02/04/2025,02/04/2025 02/04/2025 UPI/goog-payments@a/UPI/...,6.00,89529.49
3,02/04/2025,02/04/2025 02/04/2025 UPI/zomatoonlineord/Zoma...,-196.15,89333.34
4,03/04/2025,03/04/2025 03/04/2025 UPI/swiggyupi@axb/Pay fo...,-142.00,89191.34

In [22]:
# Step 4: Keep only needed columns
df = df[['Transaction Date', 'description', 'amount', 'balance']]

In [ ]:
# Clean text
df.columns = df.columns.str.lower()

In [25]:
df['description'] = df['description'].str.lower()

In [26]:
df.head()

,transaction date,description,amount,balance
0,01/04/2025,01/04/2025 01/04/2025 upi/gauravchandigar/upi/...,-38550.00,50973.49
1,01/04/2025,01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/...,38550.00,89523.49
2,02/04/2025,02/04/2025 02/04/2025 upi/goog-payments@a/upi/...,6.00,89529.49
3,02/04/2025,02/04/2025 02/04/2025 upi/zomatoonlineord/zoma...,-196.15,89333.34
4,03/04/2025,03/04/2025 03/04/2025 upi/swiggyupi@axb/pay fo...,-142.00,89191.34

In [ ]:
# Save clean file
df.to_csv("clean_transactions.csv", index=False)

In [28]:
print("✅ Clean CSV ready")

✅ Clean CSV ready

In [29]:
# Since my project is UPI-focused
upi_df = df[df['description'].str.contains('upi')]

In [ ]:
# Function for categorization of payments
def categorize(desc):
    if any(x in desc for x in ['swiggy', 'zomato', 'dominos', 'eatclub', 'mcdonald']):
        return 'food'
    elif any(x in desc for x in ['uber', 'ola', 'rapido', 'metro']):
        return 'travel'
    elif any(x in desc for x in ['amazon', 'flipkart', 'myntra', 'zepto', 'blinkit']):
        return 'shopping'
    elif any(x in desc for x in ['recharge', 'jio', 'airtel']):
        return 'bills'
    elif any(x in desc for x in ['salary']):
        return 'income'
    else:
        return 'others'

In [31]:
# Pass the description column in the function
upi_df['category'] = upi_df['description'].apply(categorize)

In [32]:
upi_df.head()

,transaction date,description,amount,balance,category
0,01/04/2025,01/04/2025 01/04/2025 upi/gauravchandigar/upi/...,-38550.00,50973.49,others
1,01/04/2025,01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/...,38550.00,89523.49,others
2,02/04/2025,02/04/2025 02/04/2025 upi/goog-payments@a/upi/...,6.00,89529.49,others
3,02/04/2025,02/04/2025 02/04/2025 upi/zomatoonlineord/zoma...,-196.15,89333.34,food
4,03/04/2025,03/04/2025 03/04/2025 upi/swiggyupi@axb/pay fo...,-142.00,89191.34,food

In [33]:
upi_df['category'].unique()

<StringArray>
['others', 'food', 'bills', 'travel', 'shopping']
Length: 5, dtype: str

In [34]:
upi_df['category'].value_counts()

category
others      674
shopping     85
food         75
bills        53
travel       11
Name: count, dtype: int64

Questions

In [37]:
# 1. Total Spending
upi_df[upi_df['amount'] < 0]['amount'].sum()

np.float64(-688308.02)

In [38]:
# 2. Category-wise Spend
upi_df.groupby('category')['amount'].sum()

category
bills        -8291.96
food        -20781.17
others     -173941.46
shopping    -26942.24
travel        -554.53
Name: amount, dtype: float64

In [52]:
upi_df['transaction_date'] = pd.to_datetime(
    upi_df['transaction_date'], 
    dayfirst=True
)

In [53]:
# Monthly Trend
upi_df.groupby(upi_df['transaction_date'].dt.to_period('M'))['amount'].sum()

transaction_date
2025-04   -64199.80
2025-05    90551.00
2025-06   -14012.29
2025-07   -44373.74
2025-08   -60816.33
2025-09   -25115.46
2025-10   -34567.54
2025-11    -2013.90
2025-12   -13838.93
2026-01   -15828.08
2026-02   -24832.81
2026-03   -21463.48
Freq: M, Name: amount, dtype: float64

In [50]:
print(upi_df.columns)

Index(['transaction_date', 'description', 'amount', 'balance', 'category'], dtype='str')

In [48]:
upi_df.columns = upi_df.columns.str.lower().str.replace(' ', '_')

In [54]:
# Top Merchants
upi_df['description'].value_counts().head(10)

description
01/04/2025 01/04/2025 upi/gauravchandigar/upi/punjab and sind/509120278822/axi7237d274c9294021847de9527a322ed8/ 38550.0 0.0 50973.49              1
01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/state bank of i/545772625245/axibeae77384585450994a6dd53268444ea 0.0 38550.0 89523.49               1
02/04/2025 02/04/2025 upi/goog-payments@a/upi/axis bank/756687000925/axi5fcfb2773b494baea4ded38a323d59e5 0.0 6.0 89529.49                         1
02/04/2025 02/04/2025 upi/zomatoonlineord/zomatoonlineord/airtel payments/509258814804/sbi2e2d88d8bcb04b11b2ed643549ce8fa1 196.15 0.0 89333.34    1
03/04/2025 03/04/2025 upi/swiggyupi@axb/pay for intent/axis bank/509324637530/axbaa610be292fb4d6badd498c5f713d431/ 142.0 0.0 89191.34             1
03/04/2025 03/04/2025 upi/ombk.aadf836635/upi/ppiw/509365237749/sbi8a0d5a1b37a1489bba2ca30ff7650e85/ 90.0 0.0 89101.34                            1
03/04/2025 03/04/2025 upi/jashansingh2209/upi/state bank of i/509384754298/sbia15ddcf4133a4be1bc40e2fdf0e39afe 0.0 1000.0 90101.34                1
03/04/2025 03/04/2025 upi/jio@citibank/jio20br000c046i/citibank corpor/509334379342/ptme4c49b533c88450ab9c56c4ebc97a646/ 249.0 0.0 89852.34       1
04/04/2025 04/04/2025 upi/q35330402@ybl/upi/yes bank limite/509414469355/sbi1f98f0c5cf1b4d26ae0268873cd0ea29/ 100.0 0.0 89752.34                  1
04/04/2025 04/04/2025 upi/9417493155@ptsb/na/state bank of i/509486203691/ptm85a4ab858d7a47819828b1ba46b66e8f 0.0 8500.0 98252.34                 1
Name: count, dtype: int64

In [55]:
upi_df.head()

,transaction_date,description,amount,balance,category
0,2025-04-01,01/04/2025 01/04/2025 upi/gauravchandigar/upi/...,-38550.00,50973.49,others
1,2025-04-01,01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/...,38550.00,89523.49,others
2,2025-04-02,02/04/2025 02/04/2025 upi/goog-payments@a/upi/...,6.00,89529.49,others
3,2025-04-02,02/04/2025 02/04/2025 upi/zomatoonlineord/zoma...,-196.15,89333.34,food
4,2025-04-03,03/04/2025 03/04/2025 upi/swiggyupi@axb/pay fo...,-142.00,89191.34,food

In [ ]:
upi_df['day'] = upi_df['transaction_date'].dt.day_name()

In [59]:
upi_df.head()

,transaction_date,description,amount,balance,category,day
0,2025-04-01,01/04/2025 01/04/2025 upi/gauravchandigar/upi/...,-38550.00,50973.49,others,Tuesday
1,2025-04-01,01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/...,38550.00,89523.49,others,Tuesday
2,2025-04-02,02/04/2025 02/04/2025 upi/goog-payments@a/upi/...,6.00,89529.49,others,Wednesday
3,2025-04-02,02/04/2025 02/04/2025 upi/zomatoonlineord/zoma...,-196.15,89333.34,food,Wednesday
4,2025-04-03,03/04/2025 03/04/2025 upi/swiggyupi@axb/pay fo...,-142.00,89191.34,food,Thursday

In [60]:
upi_df.groupby('day')['amount'].sum()

day
Friday       57840.80
Monday      -47475.01
Saturday    -75116.18
Sunday      -20422.42
Thursday    -46306.35
Tuesday     -38135.04
Wednesday   -60897.16
Name: amount, dtype: float64

In [71]:
upi_df.to_csv("upi_cleaned.csv", index=False)

In [72]:
upi_df['merchant'] = upi_df['description'].str.split('/').str[5]

In [73]:
upi_df.head(10)

,transaction_date,description,amount,balance,category,day,merchant
0,2025-04-01,01/04/2025 01/04/2025 upi/gauravchandigar/upi/...,-38550.00,50973.49,others,Tuesday,gauravchandigar
1,2025-04-01,01/04/2025 01/04/2025 upi/thappavansh2-2@/upi/...,38550.00,89523.49,others,Tuesday,thappavansh2-2@
2,2025-04-02,02/04/2025 02/04/2025 upi/goog-payments@a/upi/...,6.00,89529.49,others,Wednesday,goog-payments@a
3,2025-04-02,02/04/2025 02/04/2025 upi/zomatoonlineord/zoma...,-196.15,89333.34,food,Wednesday,zomatoonlineord
4,2025-04-03,03/04/2025 03/04/2025 upi/swiggyupi@axb/pay fo...,-142.00,89191.34,food,Thursday,swiggyupi@axb
5,2025-04-03,03/04/2025 03/04/2025 upi/ombk.aadf836635/upi/...,-90.00,89101.34,others,Thursday,ombk.aadf836635
6,2025-04-03,03/04/2025 03/04/2025 upi/jashansingh2209/upi/...,1000.00,90101.34,others,Thursday,jashansingh2209
7,2025-04-03,03/04/2025 03/04/2025 upi/jio@citibank/jio20br...,-249.00,89852.34,bills,Thursday,jio@citibank
8,2025-04-04,04/04/2025 04/04/2025 upi/q35330402@ybl/upi/ye...,-100.00,89752.34,others,Friday,q35330402@ybl
9,2025-04-04,04/04/2025 04/04/2025 upi/9417493155@ptsb/na/s...,8500.00,98252.34,others,Friday,9417493155@ptsb

In [69]:
upi_df['merchant'] = upi_df['merchant'].str.lower().str.replace(r'[^a-z]', '', regex=True)